name: build-api

on:
  workflow_call:
    inputs:
      container-version:
        required: true
        type: string
      docker-tags:
        required: true
        type: string

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          name: node
          path: ./dist
      - name: Move API
        run: |
          mv ./dist/blobtoolkit-api-linux src/docker/api/
          chmod 755 src/docker/api/blobtoolkit-api-linux
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: genomehubs/blobtoolkit-api
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: src/docker/api
          push: true
          build-args: VERSION=${{ inputs.container-version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
