name: detect-changes

on:
  workflow_call:
    outputs:
      api:
        value: ${{ jobs.detect-changes.outputs.api }}
      ui:
        value: ${{ jobs.detect-changes.outputs.ui }}
      node:
        value: ${{ jobs.detect-changes.outputs.node }}
      host:
        value: ${{ jobs.detect-changes.outputs.host }}
      pipeline:
        value: ${{ jobs.detect-changes.outputs.pipeline }}
      blobtools:
        value: ${{ jobs.detect-changes.outputs.blobtools }}
      docker:
        value: ${{ jobs.detect-changes.outputs.docker }}
      all:
        value: ${{ jobs.detect-changes.outputs.all }}
      is-host-release:
        value: ${{ jobs.is-host-release.outputs.tagged }}
      requires-node:
        value: ${{ jobs.requires-node.outputs.node }}

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      ui: ${{ steps.filter.outputs.ui }}
      node: ${{ steps.filter.outputs.node }}
      host: ${{ steps.filter.outputs.host }}
      pipeline: ${{ steps.filter.outputs.pipeline }}
      blobtools: ${{ steps.filter.outputs.blobtools }}
      docker: ${{ steps.filter.outputs.docker }}
      all: ${{ steps.filter.outputs.all }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'src/api/**'
            ui:
              - 'src/viewer/**'
              - 'src/packaged-viewer/**'
            node:
              - 'src/api/**'
              - 'src/viewer/**'
              - 'src/packaged-viewer/**'
            host:
              - 'src/blobtoolkit-host/**'
            pipeline:
              - 'src/blobtoolkit-pipeline/**'
            blobtools:
              - 'src/blobtoolkit-host/**'
              - 'src/blobtoolkit-pipeline/**'
              - 'src/blobtools/**'
              - 'src/btk/**'
            docker:
              - 'src/docker/**'
            blobtoolkit:
              - 'src/**'

  is-host-release:
    needs: detect-changes
    runs-on: ubuntu-latest
    outputs:
      tagged: ${{ steps.host-release.outputs.tagged }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - id: host-release
        run: |
          if [ ${{ needs.detect-changes.outputs.host == 'true' }} ];
            echo "tagged='true'" >> $GITHUB_OUTPUT
          fi
          echo ${{ github.ref }}

  requires-node:
    needs:
      - detect-changes
      - is-host-release
    if: always()
    runs-on: ubuntu-latest
    outputs:
      node: ${{ steps.needs-node.outputs.node }}
    steps:
      - id: needs-node
        run: |
          if [[ "${{ needs.detect-changes.outputs.node == 'true' }}" == "true" || "${{ steps.host-release.outputs.tagged == 'true' }}" == "true" ]]; then
            echo "node='true'" >> $GITHUB_OUTPUT
          fi
