name: changes

on:
  workflow_call:
    outputs:
      filter:
        description: Paths with changes
        value:
          api: ${{ jobs.changes.outputs.api }}
          ui: ${{ jobs.changes.outputs.api }}
          node: ${{ jobs.changes.outputs.api }}
      host:
        value: ${{ jobs.changes.outputs.host }}
      pipeline:
        value: ${{ jobs.changes.outputs.pipeline }}
      blobtools:
        value: ${{ jobs.changes.outputs.blobtools }}
      docker:
        value: ${{ jobs.changes.outputs.docker }}
      all:
        value: ${{ jobs.changes.outputs.all }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'src/api/**'
            ui:
              - 'src/viewer/**'
              - 'src/packaged-viewer/**'
            node:
              - 'src/api/**'
              - 'src/viewer/**'
              - 'src/packaged-viewer/**'
            host:
              - 'src/blobtoolkit-host/**'
            pipeline:
              - 'src/blobtoolkit-pipeline/**'
            blobtools:
              - 'src/blobtoolkit-host/**'
              - 'src/blobtoolkit-pipeline/**'
              - 'src/blobtools/**'
              - 'src/btk/**'
            docker:
              - 'src/docker/**'
            blobtoolkit:
              - 'src/**'
