name: package-blobtoolkit-develop
env:
  VERSION: 3.5.5

on:
  push:

jobs:
  changes:
    uses: ./.github/workflows/changes.yml

  package-api:
    needs: changes
    if: |
      needs.changes.outputs.api == 'true' ||
      needs.changes.outputs.requires-node == 'true'
    uses: ./.github/workflows/package-api.yml

  build-api:
    needs:
      - changes
      - package-api
    # if: needs.changes.outputs.is-api-release == 'true'
    secrets: inherit
    uses: ./.github/workflows/build-api.yml

  package-ui:
    needs: changes
    if: |
      needs.changes.outputs.ui == 'true' ||
      needs.changes.outputs.requires-node == 'true'
    secrets: inherit
    uses: ./.github/workflows/package-ui.yml

  build-ui:
    needs:
      - changes
      - package-ui
    # if: needs.changes.outputs.is-ui-release == 'true'
    secrets: inherit
    uses: ./.github/workflows/build-ui.yml

  package-host:
    needs:
      - changes
      - package-ui
      - package-api
    strategy:
      matrix:
        python-version: [3.9]
    if: always() && needs.changes.outputs.host == 'true'
    uses: ./.github/workflows/package-host.yml
    with:
      python-version: ${{ matrix.python-version }}

  # release-host:
  #   needs:
  #     - changes
  #     - package-host
  #   if: needs.changes.outputs.is-host-release == 'true'
  #   uses: ./.github/workflows/release-host.yml

  package-pipeline:
    needs: changes
    strategy:
      matrix:
        python-version: [3.9]
    if: needs.changes.outputs.pipeline == 'true'
    uses: ./.github/workflows/package-pipeline.yml
    with:
      python-version: ${{ matrix.python-version }}

  # release-pipeline:
  #   needs:
  #     - changes
  #     - package-pipeline
  #   if: needs.changes.outputs.is-pipeline-release == 'true'
  #   uses: ./.github/workflows/release-pipeline.yml

  package-blobtools:
    needs: changes
    strategy:
      matrix:
        python-version: [3.9]
    if: needs.changes.outputs.blobtools == 'true'
    uses: ./.github/workflows/package-blobtools.yml
    with:
      python-version: ${{ matrix.python-version }}

  # release-blobtools:
  #   needs:
  #     - changes
  #     - package-blobtools
  #     - release-host
  #     - release-pipeline
  #   if: always() && needs.changes.outputs.is-host-release == 'true'
  #   uses: ./.github/workflows/release-blobtools.yml

  build-blobtoolkit:
    needs:
      - changes
      - package-ui
      - package-api
      - package-host
      - package-pipeline
      - package-blobtools
    # if: needs.changes.outputs.is-blobtools-release == 'true'
    secrets: inherit
    uses: ./.github/workflows/build-blobtoolkit.yml
