name: package-blobtoolkit-develop
env:
  VERSION: 3.5.5

on:
  push:

jobs:
  # package-ui:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "16"
  #     - run: npm install -g pkg
  #     - run: ./package-ui.sh
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./dist/*

  # package-api:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: "16"
  #     - run: npm install -g pkg
  #     - run: ./package-api.sh
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./dist/*
  package-viewer:
    uses: ./.github/workflows/package-viewer.yml

  package-python-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build pip package
        working-directory: ./src/blobtoolkit-host
        run: |
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtoolkit-host -v
      - uses: actions/upload-artifact@v3
        with:
          path: ./src/blobtoolkit-host/dist/*

  package-python-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build pip package
        working-directory: ./src/blobtoolkit-pipeline
        run: |
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtoolkit-pipeline -v
      - uses: actions/upload-artifact@v3
        with:
          path: ./src/blobtoolkit-pipeline/dist/*

  package-python-blobtoolkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build pip package
        run: |
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtools -v
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*

  build-and-push-blobtoolkit:
    runs-on: ubuntu-latest
    needs:
      - package-api
      - package-ui
      - package-python-host
      - package-python-pipeline
      - package-python-blobtoolkit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist
      - name: Move artifacts
        run: |
          mv dist/artifact/* src/docker/
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: genomehubs/blobtoolkit
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/docker
          push: true
          tags: genomehubs/blobtoolkit:develop
          labels: ${{ steps.meta.outputs.labels }}
# build-and-push-blobtools:
#   runs-on: ubuntu-latest
#   needs: upload-to-pypi
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#     - name: Extract metadata (tags, labels) for Docker
#       id: meta
#       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#       with:
#         images: genomehubs/blobtoolkit-blobtools
#     - name: Build and push Docker image
#       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#       with:
#         context: src/docker/blobtools
#         push: true
#         tags: genomehubs/blobtoolkit-blobtools:${{ env.VERSION }}, genomehubs/blobtoolkit-blobtools:latest
#         labels: ${{ steps.meta.outputs.labels }}

# build-and-push-api:
#   runs-on: ubuntu-latest
#   needs: upload-to-pypi
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#     - name: Extract metadata (tags, labels) for Docker
#       id: meta
#       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#       with:
#         images: genomehubs/blobtoolkit-api
#     - name: Build and push Docker image
#       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#       with:
#         context: src/docker/api
#         push: true
#         tags: genomehubs/blobtoolkit-api:${{ env.VERSION }}, genomehubs/blobtoolkit-api:latest
#         labels: ${{ steps.meta.outputs.labels }}

# build-and-push-viewer:
#   runs-on: ubuntu-latest
#   needs: upload-to-pypi
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#     - name: Extract metadata (tags, labels) for Docker
#       id: meta
#       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#       with:
#         images: genomehubs/blobtoolkit-viewer
#     - name: Build and push Docker image
#       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#       with:
#         context: src/docker/viewer
#         push: true
#         tags: genomehubs/blobtoolkit-viewer:${{ env.VERSION }}, genomehubs/blobtoolkit-viewer:latest
#         labels: ${{ steps.meta.outputs.labels }}
