name: package-pipeline
on: workflow_call

jobs:
  package-python-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build pip package
        working-directory: ./src/blobtoolkit-pipeline
        run: |
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtoolkit-pipeline -v
      - uses: actions/upload-artifact@v3
        with:
          path: ./src/blobtoolkit-pipeline/dist/*
