name: package-pipeline
on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      python-version:
        required: true
        type: string

jobs:
  package-python-pipeline:
    runs-on: ubuntu-latest
    if: inputs.platform == 'linux'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build pip package
        working-directory: ./src/blobtoolkit-pipeline
        run: |
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtoolkit-pipeline -v
      - uses: actions/upload-artifact@v3
        with:
          name: pip
          path: ./src/blobtoolkit-pipeline/dist/*

  package-python-pipeline-macos:
    runs-on: macos-11
    # if: inputs.platform == 'linux'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install setuptools wheel twine
          pip3 install --upgrade cython
      - name: Build pip package
        run: |
          python3 setup.py sdist bdist_wheel --python-tag py3 --plat-name macosx_11_0_x86_64
          python3 setup.py sdist bdist_wheel --python-tag py3 --plat-name macosx_11_0_arm64
      - uses: actions/upload-artifact@v3
        with:
          name: pip
          path: ./dist/*.whl
