name: release-blobtoolkit
on:
  push:
    tags:
      - "*"
jobs:
  package-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: ./package-ui.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  package-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: ./package-api.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  package-blobtoolkit-linux:
    runs-on: ubuntu-latest
    needs:
      - package-ui
      - package-api
    steps:
      - uses: actions/checkout@v2
      - name: Collect artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./dist
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          mkdir -p src/blobtools/bin
          cp dist/artifact/*-linux src/blobtools/bin/
          chmod 755 src/blobtools/bin/*
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtools -v
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  package-blobtoolkit-macos:
    runs-on: macos-11
    needs:
      - package-ui
      - package-api
    steps:
      - uses: actions/checkout@v2
      - name: Collect artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./dist
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          mkdir -p src/blobtools/bin
          cp dist/artifact/*-macos src/blobtools/bin/
          chmod 755 src/blobtools/bin/*
          ./pip_install_latest.sh macosx_11_0_x86_64
          python3 setup.py sdist bdist_wheel --python-tag py3 --plat-name macosx_10_9_x86_64
          blobtools -v
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  package-blobtoolkit-windows:
    runs-on: ubuntu-latest
    needs:
      - package-ui
      - package-api
    steps:
      - uses: actions/checkout@v2
      - name: Collect artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./dist
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          mkdir -p src/blobtools/bin
          cp dist/artifact/*-macos src/blobtools/bin/
          chmod 755 src/blobtools/bin/*
          python3 setup.py sdist bdist_wheel --python-tag py3 --plat-name win_amd64
          ls dist
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  upload-to-pypi:
    runs-on: ubuntu-latest
    needs:
      - package-blobtoolkit-linux
      - package-blobtoolkit-macos
      - package-blobtoolkit-windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./dist
      - run: |
          mv dist/artifact/* dist/
          rm -r dist/artifact
          ls -lh dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/

  create-github-release:
    runs-on: ubuntu-latest
    needs: upload-to-pypi
    steps:
      - name: create release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          title: "v${{github.ref_name}}"
