name: package-host
on: workflow_call

jobs:
  package-python-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          name: node
          path: ./dist
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Move viewer
        run: |
          mkdir -p ./src/blobtoolkit-host/src/data/bin
          mv ./dist/*-linux ./src/blobtoolkit-host/src/data/bin/ || exit 0
      - name: Build pip package
        working-directory: ./src/blobtoolkit-host
        run: |
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtoolkit-host -v
      - uses: actions/upload-artifact@v3
        with:
          name: pip
          path: ./src/blobtoolkit-host/dist/*
