name: package-blobtoolkit-develop
env:
  VERSION: 3.5.5

on:
  push:

jobs:
  changes:
    uses: ./.github/workflows/changes.yml

  package-api:
    needs: changes
    if: |
      needs.changes.outputs.api == 'true' ||
      needs.changes.outputs.requires-node == 'true'
    uses: ./.github/workflows/package-api.yml

  build-api:
    needs:
      - changes
      - package-api
    if: needs.changes.outputs.is-api-release == 'true'
    secrets: inherit
    uses: ./.github/workflows/build-api.yml

  package-ui:
    needs: changes
    if: |
      needs.changes.outputs.ui == 'true' ||
      needs.changes.outputs.requires-node == 'true'
    secrets: inherit
    uses: ./.github/workflows/package-ui.yml

  build-ui:
    needs:
      - changes
      - package-ui
    if: needs.changes.outputs.is-ui-release == 'true'
    secrets: inherit
    uses: ./.github/workflows/build-ui.yml

  package-host:
    needs:
      - changes
      - package-ui
      - package-api
    if: always() && needs.changes.outputs.host == 'true'
    uses: ./.github/workflows/package-host.yml

  package-pipeline:
    needs: changes
    if: needs.changes.outputs.pipeline == 'true'
    uses: ./.github/workflows/package-pipeline.yml

  package-blobtools:
    needs: changes
    if: needs.changes.outputs.blobtools == 'true'
    uses: ./.github/workflows/package-blobtools.yml

  build-blobtoolkit:
    needs:
      - changes
      - package-ui
      - package-api
      - package-host
      - package-pipeline
      - package-blobtools
    if: needs.changes.outputs.is-ui-release == 'true'
    secrets: inherit
    uses: ./.github/workflows/build-blobtoolkit.yml
  # build-and-push-blobtoolkit:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - package-viewer
  #     - package-python-host
  #     - package-python-pipeline
  #     - package-python-blobtools
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Collect artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: ./dist
  #     - name: Move artifacts
  #       run: |
  #         mv dist/artifact/* src/docker/
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
  #       with:
  #         images: genomehubs/blobtoolkit
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
  #       with:
  #         context: src/docker
  #         push: true
  #         tags: genomehubs/blobtoolkit:develop
  #         labels: ${{ steps.meta.outputs.labels }}
