name: test-blobtoolkit
on: [push]
jobs:
  update-btk:
    runs-on: ubuntu-latest
    container:
      image: genomehubs/blobtoolkit-blobtools:latest
      ports:
        - 8000
        - 8001
      volumes:
        - /home/runner/work/blobtoolkit/blobtoolkit:/blobtoolkit/conf
    steps:
      - run: yes | pip uninstall blobtoolkit
      - run: yes | pip install blobtoolkit

  package-ui:
    runs-on: ubuntu-latest
    needs:
      - update-btk
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: ./package-ui.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  package-api:
    runs-on: ubuntu-latest
    needs:
      - update-btk
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: ./package-api.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  package-blobtoolkit-linux:
    runs-on: ubuntu-latest
    needs:
      - package-ui
      - package-api
    steps:
      - uses: actions/checkout@v2
      - name: Collect artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./dist
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          mkdir -p src/data/bin
          cp dist/artifact/*-linux src/data/bin/
          rm -r dist/artifact
          chmod 755 src/data/bin/*
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtools -v
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  test-commands:
    runs-on: ubuntu-latest
    needs:
      - package-blobtoolkit-linux
    steps:
      - uses: actions/checkout@v2
      - name: Collect artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./dist
      - name: Pip install blobtoolkit
        run: |
          python3 -m pip install --upgrade pip
          pip install dist/artifact/*linux*.whl
          rm -r dist/artifact
          blobtools -v
      - run: |
          (blobtools host --port 8001 --api-port 8000 _ &)
          sleep 30
          netstat -lt
      - name: Install dependencies
        run: sudo apt-get install -y chromium-browser chromium-chromedriver firefox xvfb
      - run: |
          netstat -lt
          which Chrome || \
          which chrome && alias Chrome=$(which chrome)
          which chromium && alias Chrome=$(which chromium) || echo no chromium
          which chromedriver || echo no chromedriver
      - name: Generate static plot
        run: |
          blobtools view \
              --host http://localhost \
              --driver chromium \
              --timeout 60 \
              --ports 8000-8099 \
              --view blob \
              --param plotShape=circle \
              --param largeFonts=true \
              --format png \
              _
      - name: Test plot exists
        run: |
          test -s "FXWY01.blob.circle.png" && exit 0 || exit 1
      - uses: actions/upload-artifact@v2
        with:
          name: tests
          path: FXWY01.blob.circle.png
