name: test-blobtoolkit
on: workflow_dispatch

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'src/api/**'
            viewer:
              - 'src/viewer/**'
              - 'src/packaged-viewer/**'
            node:
              - 'src/api/**'
              - 'src/viewer/**'
              - 'src/packaged-viewer/**'
            host:
              - 'src/blobtoolkit-host/**'
            pipeline:
              - 'src/blobtoolkit-pipeline/**'
            blobtools:
              - 'src/blobtoolkit-host/**'
              - 'src/blobtoolkit-pipeline/**'
              - 'src/blobtools/**'
              - 'src/btk/**'
            docker:
              - 'src/docker/**'
            blobtoolkit:
              - 'src/**'

  package-api:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    uses: ./.github/workflows/package-api.yml

  package-viewer:
    needs: changes
    if: ${{ needs.changes.outputs.viewer == 'true' }}
    uses: ./.github/workflows/package-viewer.yml

  package-node:
    needs: changes
    if: ${{ needs.changes.outputs.node == 'true' }}
    uses: ./.github/workflows/package-node.yml

  package-blobtoolkit-linux:
    runs-on: ubuntu-latest
    needs:
      - package-ui
      - package-api
    steps:
      - uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          mkdir -p src/data/bin
          cp dist/artifact/*-linux src/data/bin/
          rm -r dist/artifact
          chmod 755 src/data/bin/*
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtools -v
      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*

  test-commands:
    runs-on: ubuntu-latest
    needs:
      - package-blobtoolkit-linux
    steps:
      - uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist
      - name: Pip install blobtoolkit
        run: |
          python3 -m pip install --upgrade pip
          pip install dist/artifact/*linux*.whl
          rm -r dist/artifact
          blobtools -v
      - name: Install dependencies
        run: sudo apt-get install -y firefox xvfb
      - name: Generate static plot
        run: |
          blobtools view \
              --host http://localhost \
              --timeout 60 \
              --ports 8000-8099 \
              --view blob \
              --param plotShape=circle \
              --param largeFonts=true \
              --format png \
              _
      - name: Test plot exists
        run: |
          test -s "FXWY01.blob.circle.png" && exit 0 || exit 1
      - uses: actions/upload-artifact@v3
        with:
          name: tests
          path: FXWY01.blob.circle.png
