name: upload-to-pypi
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  upload-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          path: ./tmp
          pattern: pip-*
      - run: |
          mkdir -p ./dist
          COMPONENT=${{ inputs.component }}
          mv tmp/pip-*/${{ inputs.component }}-*-*.whl dist/
          mv tmp/pip-*/${COMPONENT/_/-}-*.tar.gz dist/
      - name: Check if version exists on PyPI
        id: check-version
        run: |
          PACKAGE_NAME=${{ inputs.component }}
          VERSION=${{ inputs.version }}
          if curl -s https://pypi.org/pypi/$PACKAGE_NAME/$VERSION/json | grep -q '"version": "'$VERSION'"'; then
            echo "Version $VERSION of $PACKAGE_NAME already exists on PyPI."
            exit 0
          else
            echo "Version $VERSION of $PACKAGE_NAME does not exist on PyPI."
          fi
      - name: Publish package to PyPI
        if: steps.check-version.outputs.version_exists == 'false'
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
